name: Run CORS Anywhere Proxy

on:
  push:
    branches:
      - main  # veya kullanmak istediğiniz ana dal adı

jobs:
  run-cors-anywhere:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Node.js sürümünü seçin (uygun bir sürüm)

      - name: Install dependencies
        run: npm install  # package.json içindeki bağımlılıkları yükler

      - name: Set environment variables
        env:
          HOST: '0.0.0.0'  # Opsiyonel olarak HOST değerini ayarlayabilirsiniz
          PORT: 8080  # Opsiyonel olarak PORT değerini ayarlayabilirsiniz
          CORSANYWHERE_BLACKLIST: ''  # Opsiyonel olarak CORSANYWHERE_BLACKLIST değerini ayarlayabilirsiniz
          CORSANYWHERE_WHITELIST: ''  # Opsiyonel olarak CORSANYWHERE_WHITELIST değerini ayarlayabilirsiniz
          CORSANYWHERE_RATELIMIT: '100'  # Opsiyonel olarak CORSANYWHERE_RATELIMIT değerini ayarlayabilirsiniz

      - name: Start CORS Anywhere Proxy
        run: node server.js  # server.js dosyasını başlatır
