name: Run cors-anywhere

on:
  push:
    branches:
      - main  # Ana dalda değişiklik olduğunda çalıştır
  pull_request:
    branches:
      - main  # Ana dalda pull request olduğunda çalıştır

jobs:
  run-cors-anywhere:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Start cors-anywhere server
        run: |
          npm start &
          echo "Waiting for server to start..."
          sleep 10  # Serverın başlaması için bekleme süresi

      - name: Test server
        run: |
          echo "Sending test request..."
          curl -I http://localhost:8080/

      - name: Stop server
        run: |
          echo "Stopping server..."
          npm stop
